name: Node.js CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Github Action
        uses: ./.github/workflows/setup
      - run: pnpm install
      - run: pnpm run typecheck
      - run: pnpm run assert
      - run: pnpm run lint
      - run: pnpm run prettier
      - run: pnpm run jest
